[package]
name = "siws"
version = "0.1.0"
license = "MIT"
description = "Lightweight Sign in With Solana library adhering to the Solana Wallet Standard."
homepage = "https://github.com/MeteoraAg/siws-rs"
repository = "https://github.com/MeteoraAg/siws-rs"
readme = "README.md"
authors = ["Hoang Trinh <hoang.trinhj@gmail.com>"]
keywords = ["solana", "sign-in", "siws"]
categories = ["authentication", "cryptography::cryptocurrencies"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive", "std"] }
ed25519-dalek = "2"
base64 = "0.22"
bs58 = "0.5.1"
thiserror = "2"
time = { version = "0.3.36", features = ["parsing", "formatting"] }
iri-string = "0.7"

[dev-dependencies]
serde_json = "1.0.115"
rand = "0.10.0"
matches = "0.1.10"
